services:

  astro:
    image: node:22-alpine
    ports:
      - 127.0.0.1:4321:4321
      - 127.0.0.1:5173:5173
    environment:
      - YARN_CACHE_FOLDER=/home/node/cache/yarn
      - VITE_HOST=0.0.0.0
      - VITE_PORT=5173
    volumes:
      - ${PWD}/:/app:cached
    working_dir: /app
    user: node
    stdin_open: true
    tty: true